import { Idea } from '../types/idea';
import { Project } from '../types/project';

const now = new Date();
const daysAgo = (days: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const INITIAL_IDEAS: Idea[] = [
  {
    id: 'idea-1',
    _id: 'mongo_id_001',
    title: 'AI Resume Reviewer',
    description: 'An AI-powered ATS resume scanner and optimization tool that parses PDFs, identifies missing industry keywords, scores readability, and suggests high-impact bullet point rewrites tailored to target job descriptions.',
    type: 'idea',
    status: 'building',
    mood: 'inspired',
    priority: 'urgent',
    isFavorite: true,
    tags: ['ai', 'career', 'web', 'mern'],
    checklist: [
      { id: 'c1', text: 'Define ATS scoring heuristics & keyword parser', completed: true },
      { id: 'c2', text: 'Implement PDF text extraction pipeline', completed: true },
      { id: 'c3', text: 'Build interactive score breakdown UI', completed: false },
      { id: 'c4', text: 'Test LLM prompt with 20 real recruiter job descriptions', completed: false },
    ],
    problemStatement: 'Candidates send hundreds of applications that get rejected by automated ATS filters before a human recruiter even sees them.',
    solutionStatement: 'Real-time resume scoring with actionable bullet-point diffs matching specific job requisitions.',
    resurfacedCount: 3,
    lastResurfacedAt: daysAgo(2),
    createdAt: daysAgo(132), // 132 days ago for resurfacing showcase!
    updatedAt: daysAgo(1),
  },
  {
    id: 'idea-2',
    _id: 'mongo_id_002',
    title: 'Buoyant Stall Booking UX',
    description: 'Interactive canvas/SVG event hall visualizer for booking conference and exhibition vendor stalls in real-time. Features live occupancy pulses, dynamic pricing tiers, and vendor proximity insights.',
    type: 'idea',
    status: 'idea',
    mood: 'creative',
    priority: 'high',
    isFavorite: true,
    tags: ['startup', 'web', 'ui-ux'],
    checklist: [
      { id: 'c5', text: 'Draft 2D floor plan coordinate system', completed: true },
      { id: 'c6', text: 'Design stall hover card with power & foot-traffic metrics', completed: false },
      { id: 'c7', text: 'Integrate Stripe micro-deposits for instant stall hold', completed: false },
    ],
    problemStatement: 'Event organizers use confusing static PDF maps and back-and-forth emails to allocate expensive exhibition stalls.',
    solutionStatement: 'Figma-smooth interactive booking map with pinch-to-zoom and instant stall reservations.',
    resurfacedCount: 1,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(5),
  },
  {
    id: 'idea-3',
    _id: 'mongo_id_003',
    title: 'Personal Finance Adviser',
    description: 'A privacy-first zero-based budgeting assistant. Imports bank statements via Open Banking or manual CSV, categorizes cashflow locally on device, and calculates financial runway with visual Monte Carlo simulations.',
    type: 'idea',
    status: 'building',
    mood: 'curious',
    priority: 'urgent',
    isFavorite: true,
    tags: ['finance', 'mobile', 'startup'],
    checklist: [
      { id: 'c8', text: 'Local AES-256 SQLite database layer', completed: true },
      { id: 'c9', text: 'Envelope budgeting math model', completed: true },
      { id: 'c10', text: 'Runway projection visualizer charts', completed: false },
    ],
    problemStatement: 'Most finance apps sell user transaction data and force clunky subscription upsells without offering actual wealth insights.',
    solutionStatement: 'Offline-first, client-encrypted financial intelligence assistant that respects data privacy.',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
  },
  {
    id: 'idea-4',
    _id: 'mongo_id_004',
    title: 'Trading Journal & Mindset Tracker',
    description: 'A specialized journaling tool for day traders and swing traders. Logs entry/exit execution, risk-to-reward ratio, rule adherence, and psychological mindset at time of execution.',
    type: 'note',
    status: 'idea',
    mood: 'calm',
    priority: 'medium',
    isFavorite: false,
    tags: ['finance', 'random'],
    checklist: [
      { id: 'c11', text: 'Define pre-market emotional state checklist', completed: true },
      { id: 'c12', text: 'Calculate win-rate by emotion tag (e.g. FOMO vs Disciplined)', completed: false },
    ],
    createdAt: daysAgo(88),
    updatedAt: daysAgo(12),
  },
  {
    id: 'idea-5',
    _id: 'mongo_id_005',
    title: 'MERN Interview Question Bank & Tracker',
    description: 'Curated technical interview prep dashboard for Fullstack MERN engineers. Includes Node.js event loop deep-dives, React 19 reconciliation patterns, MongoDB indexing optimization quizzes, and spaced repetition flashcards.',
    type: 'learning',
    status: 'building',
    mood: 'energized',
    priority: 'high',
    isFavorite: true,
    tags: ['mern', 'career', 'web'],
    checklist: [
      { id: 'c13', text: 'Catalog 50 advanced Node.js microtask/macrotask scenarios', completed: true },
      { id: 'c14', text: 'Build React fiber architecture interactive breakdown', completed: true },
      { id: 'c15', text: 'Add mock interview question timer', completed: false },
    ],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: 'idea-6',
    _id: 'mongo_id_006',
    title: 'Minimalist Portfolio Builder',
    description: 'CLI and web generator that turns a single `profile.json` or Markdown folder into a blazingly fast portfolio website with dark mode, RSS feed, and GitHub pinned project stats.',
    type: 'idea',
    status: 'parked',
    mood: 'creative',
    priority: 'low',
    isFavorite: false,
    tags: ['web', 'portfolio'],
    checklist: [
      { id: 'c16', text: 'Create Tailwind modern templates', completed: true },
      { id: 'c17', text: 'Add GitHub GraphQL API contribution graph fetcher', completed: false },
    ],
    createdAt: daysAgo(105),
    updatedAt: daysAgo(20),
  },
  {
    id: 'idea-7',
    _id: 'mongo_id_007',
    title: 'React Native Expense Tracker',
    description: 'Ultra-fast offline expense tracker designed for 1-handed phone use. Features optical receipt scanning, automatic currency conversion, and instant export to Google Sheets or Notion.',
    type: 'idea',
    status: 'building',
    mood: 'energized',
    priority: 'high',
    isFavorite: true,
    tags: ['mobile', 'finance', 'startup'],
    checklist: [
      { id: 'c18', text: 'Expo Camera + OCR text extraction demo', completed: true },
      { id: 'c19', text: 'Zustand offline persistent store', completed: true },
      { id: 'c20', text: 'Smooth swipe-to-delete transaction animations', completed: false },
    ],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
  },
  {
    id: 'idea-8',
    _id: 'mongo_id_008',
    title: 'Linux Setup & Dotfiles Optimization',
    description: 'Comprehensive setup guide for Arch Linux and Fedora workstations. Tmux keybindings, Neovim LSP configuration, zsh plugins, Wayland gestures, and battery power profiles for ThinkPads.',
    type: 'note',
    status: 'completed',
    mood: 'calm',
    priority: 'medium',
    isFavorite: false,
    tags: ['linux', 'random'],
    checklist: [
      { id: 'c21', text: 'Backup Neovim lua config to private GitHub repo', completed: true },
      { id: 'c22', text: 'Tune battery thresholds using TLP & powertop', completed: true },
      { id: 'c23', text: 'Configure automated dotfiles symlinking script', completed: true },
    ],
    createdAt: daysAgo(90),
    updatedAt: daysAgo(15),
  },
  {
    id: 'idea-9',
    _id: 'mongo_id_009',
    title: 'Career Roadmap to Principal Engineer',
    description: 'Strategic milestone tracking: high-leverage architectural designs, cross-team influence, open source RFC contributions, mentoring junior developers, and publishing engineering whitepapers.',
    type: 'goal',
    status: 'building',
    mood: 'inspired',
    priority: 'urgent',
    isFavorite: true,
    tags: ['career'],
    checklist: [
      { id: 'c24', text: 'Write technical design document for scalable event queue', completed: true },
      { id: 'c25', text: 'Present system design workshop to engineering team', completed: true },
      { id: 'c26', text: 'Contribute patch to popular open-source TypeScript tool', completed: false },
      { id: 'c27', text: 'Host bi-weekly 1-on-1 mentorship sessions', completed: false },
    ],
    createdAt: daysAgo(21),
    updatedAt: daysAgo(2),
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'project-1',
    _id: 'mongo_proj_001',
    ideaId: 'idea-1',
    title: 'AI Resume Reviewer',
    description: 'Fullstack AI platform that analyzes engineering and product resumes, flags ATS parsing issues, and generates tailored rewrite recommendations.',
    problem: 'Job seekers have low application response rates due to resume formatting errors and mismatched keyword densities.',
    solution: 'Automated semantic parsing, keyword frequency comparison against target job listings, and LLM-guided bullet revisions.',
    features: [
      'Multi-page PDF parsing with formatting preservation',
      'Real-time ATS compatibility score (0-100%)',
      'Missing skills & competencies heatmap',
      'One-click AI bullet rewrite suggestions',
      'Export optimized PDF and LaTeX',
    ],
    techStack: ['React Native', 'Expo', 'TypeScript', 'Node.js', 'Express', 'MongoDB', 'OpenAI API'],
    tasks: [
      { id: 'pt1', title: 'Implement PDF file upload and text extraction', completed: true },
      { id: 'pt2', title: 'Write ATS keyword extraction regex & tokenizer', completed: true },
      { id: 'pt3', title: 'Design modern score ring and breakdown metrics', completed: true },
      { id: 'pt4', title: 'Build job description comparison diff view', completed: false },
      { id: 'pt5', title: 'Set up Stripe checkout for premium reviews', completed: false },
    ],
    nextAction: 'Finalize job description comparison diff view and prompt tuning.',
    notes: 'Prioritize privacy: never store raw user resumes without user opt-in.',
    deadline: '2026-10-31',
    status: 'building',
    tags: ['ai', 'career', 'mern'],
    progress: 60,
    timeline: [
      { id: 'tl1', date: '132 days ago', title: 'Idea Captured', description: 'Noticed friends struggling with tech resume screens.' },
      { id: 'tl2', date: '60 days ago', title: 'Converted to Project', description: 'Defined technical spec and MVP requirements.' },
      { id: 'tl3', date: '14 days ago', title: 'Core PDF Parser Verified', description: 'Tested against 50 standard resume templates.' },
    ],
    resources: [
      { id: 'r1', title: 'ATS Industry Standards Guide', url: 'https://example.com/ats-standards' },
      { id: 'r2', title: 'OpenAI Structured Outputs Doc', url: 'https://platform.openai.com/docs' },
    ],
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: 'project-2',
    _id: 'mongo_proj_002',
    ideaId: 'idea-3',
    title: 'Personal Finance Adviser',
    description: 'Privacy-focused financial dashboard with zero-based budgeting, investment portfolio tracking, and local encrypted storage.',
    problem: 'Existing apps leak banking data to data brokers and lack intelligent scenario simulations.',
    solution: '100% on-device calculations, offline SQLite persistence, and Monte Carlo financial independence projections.',
    features: [
      'Local-first zero-based budgeting envelopes',
      'Bank statement CSV importer with auto-rule categorization',
      'Net worth & cashflow trend curves',
      'Monte Carlo retirement runway simulator',
    ],
    techStack: ['React Native', 'TypeScript', 'Zustand', 'AsyncStorage', 'TailwindCSS'],
    tasks: [
      { id: 'pt6', title: 'Build transaction categorization engine', completed: true },
      { id: 'pt7', title: 'Implement envelope budgeting monthly resets', completed: true },
      { id: 'pt8', title: 'Add interactive cashflow chart with pan & zoom', completed: false },
      { id: 'pt9', title: 'Encrypted JSON backup and restore flow', completed: false },
    ],
    nextAction: 'Integrate cashflow visualizer and category breakdown charts.',
    notes: 'Keep local encryption keys in secure hardware enclave.',
    deadline: '2026-11-15',
    status: 'building',
    tags: ['finance', 'mobile', 'startup'],
    progress: 50,
    timeline: [
      { id: 'tl4', date: '60 days ago', title: 'Idea Conceived', description: 'Dissatisfied with current budgeting apps.' },
      { id: 'tl5', date: '30 days ago', title: 'Architecture Approved', description: 'Decided on offline-first React Native model.' },
    ],
    resources: [
      { id: 'r3', title: 'Zero-Based Budgeting Principles', url: 'https://example.com/zero-based' },
    ],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(3),
  },
  {
    id: 'project-3',
    _id: 'mongo_proj_003',
    ideaId: 'idea-7',
    title: 'React Native Expense Tracker',
    description: 'Lightning-fast mobile expense recording tool with camera receipts and seamless offline sync.',
    problem: 'Recording small daily expenses is tedious and requires too many clicks.',
    solution: '1-tap quick capture from notification shade or widget, smart receipt OCR, and instant category learning.',
    features: [
      'Single-tap bottom sheet expense capture',
      'OCR receipt total and merchant detector',
      'Recurring subscription tracker',
      'Weekly progress summary widget',
    ],
    techStack: ['React Native', 'Expo Router', 'NativeWind', 'Zod', 'Reanimated'],
    tasks: [
      { id: 'pt10', title: 'Design high-speed numpad input screen', completed: true },
      { id: 'pt11', title: 'Build merchant auto-suggestion database', completed: true },
      { id: 'pt12', title: 'Camera receipt crop and scanner UI', completed: true },
      { id: 'pt13', title: 'Notion API two-way sync adapter', completed: false },
    ],
    nextAction: 'Finish Notion API webhook synchronization.',
    notes: 'Must launch capture screen in under 400ms.',
    deadline: '2026-09-30',
    status: 'building',
    tags: ['mobile', 'finance'],
    progress: 75,
    timeline: [
      { id: 'tl6', date: '14 days ago', title: 'Started Build', description: 'Created initial Expo Router scaffold.' },
      { id: 'tl7', date: '4 days ago', title: 'Camera OCR Working', description: 'Tested receipt capture with 95% accuracy.' },
    ],
    resources: [
      { id: 'r4', title: 'Expo Camera Documentation', url: 'https://docs.expo.dev/versions/latest/sdk/camera/' },
    ],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(1),
  },
];

export const POPULAR_TAGS = [
  'mern',
  'startup',
  'finance',
  'career',
  'mobile',
  'web',
  'ai',
  'random',
  'portfolio',
  'linux',
  'ui-ux',
];

export const MOTIVATIONAL_QUOTES = [
  { quote: 'Your mind is for having ideas, not holding them.', author: 'David Allen' },
  { quote: 'An idea that is not dangerous is unworthy of being called an idea at all.', author: 'Oscar Wilde' },
  { quote: 'Ideas are easy. Implementation is everything.', author: 'Guy Kawasaki' },
  { quote: 'Turn your sparks into flame, and your flame into architecture.', author: 'Idea Vault' },
];
